services:
  ros2-robotic-arm:
    image: ros2-robotic-arm
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth  # Added for security/auth
    volumes:    c
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # Added :rw (read-write)
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw # Added for auth
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true